namespace Styx.WoWInternals.WoWObjects
{
    public enum WoWPlayerCombatRating
    {
        WeaponSkill,
        DefenseSkill,
        Dodge,
        Parry,
        Block,
        HitMelee,
        HitRanged,
        HitSpell,
        CritMelee,
        CritRanged,
        CritSpell,
        HitTakenMelee,
        HitTakenRanged,
        HitTakenSpell,
        ResilienceCritTaken,
        ResiliencePlayerDamageTaken,
        CritTakenSpell,
        HasteMelee,
        HasteRanged,
        HasteSpell,
        WeaponSkillMainHand,
        WeaponSkillOffHand,
        WeaponSkillRanged,
        Expertise,
        ArmorPenetration
    }
}
