using System;

namespace Styx.Offsets
{
	/// <summary>
	/// Item descriptor field indices for WoW 3.3.5a (Build 12340).
	/// These are byte offsets from the item descriptor base.
	/// Item descriptors start after OBJECT_END (0x6).
	/// </summary>
	public enum WoWItemFields : uint
	{
		ITEM_FIELD_OWNER = 0x0,                  // Size 2 (GUID)
		ITEM_FIELD_CONTAINED = 0x2,              // Size 2 (GUID)
		ITEM_FIELD_CREATOR = 0x4,                // Size 2 (GUID)
		ITEM_FIELD_GIFTCREATOR = 0x6,            // Size 2 (GUID)
		ITEM_FIELD_STACK_COUNT = 0x8,
		ITEM_FIELD_DURATION = 0x9,
		ITEM_FIELD_SPELL_CHARGES = 0xA,          // 5 entries
		ITEM_FIELD_SPELL_CHARGES_01 = 0xB,
		ITEM_FIELD_SPELL_CHARGES_02 = 0xC,
		ITEM_FIELD_SPELL_CHARGES_03 = 0xD,
		ITEM_FIELD_SPELL_CHARGES_04 = 0xE,
		ITEM_FIELD_FLAGS = 0xF,
		ITEM_FIELD_ENCHANTMENT_1_1 = 0x10,       // 3 entries per enchant, 15 enchants = 45 entries total
		ITEM_FIELD_ENCHANTMENT_1_3 = 0x12,
		ITEM_FIELD_ENCHANTMENT_2_1 = 0x13,
		ITEM_FIELD_ENCHANTMENT_2_3 = 0x15,
		ITEM_FIELD_ENCHANTMENT_3_1 = 0x16,
		ITEM_FIELD_ENCHANTMENT_3_3 = 0x18,
		ITEM_FIELD_ENCHANTMENT_4_1 = 0x19,
		ITEM_FIELD_ENCHANTMENT_4_3 = 0x1B,
		ITEM_FIELD_ENCHANTMENT_5_1 = 0x1C,
		ITEM_FIELD_ENCHANTMENT_5_3 = 0x1E,
		ITEM_FIELD_ENCHANTMENT_6_1 = 0x1F,
		ITEM_FIELD_ENCHANTMENT_6_3 = 0x21,
		ITEM_FIELD_ENCHANTMENT_7_1 = 0x22,
		ITEM_FIELD_ENCHANTMENT_7_3 = 0x24,
		ITEM_FIELD_ENCHANTMENT_8_1 = 0x25,
		ITEM_FIELD_ENCHANTMENT_8_3 = 0x27,
		ITEM_FIELD_ENCHANTMENT_9_1 = 0x28,
		ITEM_FIELD_ENCHANTMENT_9_3 = 0x2A,
		ITEM_FIELD_ENCHANTMENT_10_1 = 0x2B,
		ITEM_FIELD_ENCHANTMENT_10_3 = 0x2D,
		ITEM_FIELD_ENCHANTMENT_11_1 = 0x2E,
		ITEM_FIELD_ENCHANTMENT_11_3 = 0x30,
		ITEM_FIELD_ENCHANTMENT_12_1 = 0x31,
		ITEM_FIELD_ENCHANTMENT_12_3 = 0x33,
		ITEM_FIELD_ENCHANTMENT_13_1 = 0x34,
		ITEM_FIELD_ENCHANTMENT_13_3 = 0x36,
		ITEM_FIELD_ENCHANTMENT_14_1 = 0x37,
		ITEM_FIELD_ENCHANTMENT_14_3 = 0x39,
		ITEM_FIELD_ENCHANTMENT_15_1 = 0x3A,
		ITEM_FIELD_ENCHANTMENT_15_3 = 0x3C,
		ITEM_FIELD_PROPERTY_SEED = 0x3D,
		ITEM_FIELD_RANDOM_PROPERTIES_ID = 0x3E,
		ITEM_FIELD_DURABILITY = 0x3F,
		ITEM_FIELD_MAXDURABILITY = 0x40,
		ITEM_FIELD_CREATE_PLAYED_TIME = 0x41,
		ITEM_FIELD_PAD = 0x42,
		ITEM_END = 0x43
	}
}
