#nullable disable

namespace Styx.Logic.Combat
{
    /// <summary>
    /// Represents the various spell focus requirements in World of Warcraft.
    /// Some spells require the player to be near specific objects (like anvils, forges, etc.).
    /// </summary>
    public enum WoWSpellFocus
    {
        None,
        Anvil,
        Loom,
        Forge,
        CookingFire,
        ShardsOfMyzrael,
        WinterhoofWaterWell,
        ThunderhornWaterWell,
        WildmaneWaterWell,
        TribalFire,
        MachineShop,
        ShadowglenMoonwell,
        StarbreezeVillageMoonwell,
        PoolsOfArlithrienMoonwell,
        OracleGladeMoonwell,
        VentureCoAirport,
        VentureCoWagonBlue,
        VentureCoWagonRed,
        Ng5ExplosivesRed,
        Ng5ExplosivesBlue,
        FlameOfUzel,
        AshenvaleMoonwell,
        SeawornAltar,
        NearbyTubers,
        UndercitySummoningCircle = 43,
        ShamanShrine = 63,
        StormwindSummoningCircle = 83,
        BarrensSummoningCircle = 103,
        MirrorLakeWaterfall = 123,
        TalonDen = 143,
        XavianWaterfall = 163,
        StoneOfOuterBinding,
        ManaRiftDisturbance = 183,
        OrgrimmarSummoningCircle = 203,
        RuinsOfStardustFountain = 223,
        QuilboarWateringHole,
        WaterPuritySilverpine,
        SpringWell,
        TempleOfTheMoonFountain = 243,
        JinthaAlorAltar = 263,
        PirateShipBilge,
        EquinexMonolith = 283,
        WitherbarkVillage = 303,
        ShadraAlorAltar,
        SandsorrowWatchWaterHole = 323,
        HatetalonStones = 343,
        EcheyakeesLair = 363,
        TheDeadTree = 383,
        MakeshiftHelipad = 403,
        CircleOfAquementas = 423,
        SanctumOfTheFallenGod,
        TheFirstTidePool = 443,
        TheSecondTidePool,
        TheThirdTidePool,
        TheFourthTidePool,
        GorishiHiveHatchery = 463,
        MiblonSnarltooth = 483,
        GadgetzanGraveyard = 503,
        TheRuinsOfIrontreeWoods = 523,
        BlackForge = 543,
        GolakkaCrater = 563,
        TombOfTheSeven = 583,
        FlatUnGoroRock = 603,
        PreservedThreshadonCarcass,
        BlackAnvil = 623,
        GorishiSilithidCrystal = 643,
        CorruptedMoonwell,
        AlchemyLab = 663,
        UnforgedSealOfAscension = 683,
        AuberdineMoonwell = 703,
        BlackwoodFurbolgNorthBonfire,
        CliffspringRiverWaterfall,
        FirePlumeRidgeHotSpot = 723,
        UroksTributePile = 743,
        AndorhalSiloTemporalRift = 763,
        StoneOfShyRotam = 783,
        SacredFireOfLife = 803,
        ScarletCrusadeForwardCamp,
        AndorhalTower,
        ScholomanceViewingRoom = 823,
        TheJaedenarCorruptMoonWell = 843,
        UmisFriend = 863,
        Moonwell = 883,
        FirePlumeRidgeLavaLake = 903,
        TheCrateInTheCenterOfTheNorthridgeLumberMill = 923,
        MoonkinStone = 943,
        DarrowshireTownSquare,
        BrightLightBeam = 963,
        MarkOfDetonation = 983,
        CliffspringFallsCaveMouth = 1003,
        DreadmistPeakPool,
        TheDeadGoliaths = 1023,
        ShrineOfRemulos = 1043,
        FoulwealdTotemMound = 1063,
        DirePool = 1083,
        MaraudonPortal = 1103,
        HordeGlobeOfScrying = 1123,
        EasternCrater = 1143,
        WesternCrater,
        SnowfallGraveyard,
        AllianceGlobeOfScrying = 1163,
        DunBaldarCourtyard,
        FrostwolfKeepCourtyard,
        SnowfallGraveyard2 = 1183,
        EastCrater,
        WestCrater,
        OrangeCrystalPool = 1203,
        OnyxiasFlameBreath = 1223,
        KroshiusRemains = 1243,
        PedestalOfImmolThar = 1263,
        CircleOfDarkSummoning,
        TheGreatOssuary = 1283,
        TerrordaleHauntingSpirit,
        AeriePeakTownCenter = 1303,
        UthersTombStatue = 1323,
        GromsMonument,
        PaglesPointe = 1343,
        AltarOfZanza,
        Southshore,
        BonesOfGrakkarond,
        ForsakenStinkBomb,
        DropOffPoint,
        SwirlingMaelstrom,
        HighChiefWinterfallsCave,
        FireworkLauncher,
        ClusterLauncher,
        GreaterMoonlight,
        VoonesChamber,
        AlzzinsChamber,
        TheCrimsonThrone,
        RasFrostwhispersChamber,
        TheBeastsChamber,
        HauntedLocus,
        BlackrockDepthsArena,
        PhCrystalCorpse,
        IcebellowAnvil,
        EversongRunestone,
        ConsecratedEarth,
        MidsummerBonfire,
        Maypole,
        AltarOfAggonar,
        BonesOfAggonar,
        SchoolOfRedSnapper,
        KrunSpinebreakersCorpse,
        ThalanaarMoonwell,
        ConcealedControlPanel,
        AltarOfNaias,
        DiscreetLocation,
        RuneOfSummoning,
        FelBrazier,
        YouToBeInTraitorsCoveWhileTheNagaFlagIsUp,
        SedaisCorpse,
        NazzivusMonument,
        ImpactSiteCrystal,
        AlteredBloodmystCrystal,
        AxxarienCrystal,
        TheSouthernEndOfTheMastersTerrace,
        MedivhsTelescope,
        AlonsusChapelEternalFlame,
        BloodmystWaterfall,
        SteamPumpControls,
        WindyreedHut,
        EarthenBrand,
        UndergroundWaterSource,
        BohaMuRuinsStairs,
        DaggerfenRock,
        BurningBladePyreInTheBurningBladeRuins,
        YsielsBalcony,
        BlazingWarmaulPyre,
        VeilShalasTotem,
        TrampledSkeleton,
        AllianceCannon,
        HordeBladeThrower,
        LegionAntenna,
        ScorchedGroveRunestone,
        Bookcase,
        WeaponRack,
        Dresser,
        Footlocker,
        RuinedAllianceSiegeTower,
        UncontrolledScrapReaverX6000,
        KirinVarRune,
        ArchmageVargothsOrb,
        ElrendarFalls,
        DragonSkeleton,
        EtherealTeleportPad,
        ArklonBrazier,
        VoidStone,
        ManaforgeBNaarPipe,
        DraeneiBanner,
        EarthbindersCircle,
        SalhadaarsPowerConduit,
        SocretharsTeleporter,
        EcoDomeSuthronGenerator,
        YouToBeCloserToManaforgeUltris,
        NorthmaulTower,
        AltarOfShadows,
        ShadowmoonTuberMound,
        RokgahBloodgrip,
        ManaLoom,
        AncientDraeneiAltar,
        OgreBuildingEntrance,
        BladesEdgeArakkoaCircle,
        LashhAnSpellCircle,
        VekhNirCircleOfPower,
        YouToBeAtTheEndOfTheBridge,
        TorgossBane,
        VekhNirSpellCircle,
        YouToBeStandingNextToGulDanAtTheAltarOfDamnation,
        LegionHoldTeleporter,
        RuuanOkOracleCircle,
        LegionCommunicationDevice,
        ForemanRazelcraz,
        PortalAtMarshlightLake,
        BladesEdgeQuestBirdSpying,
        MalukazsCandles,
        BleedingHollowForge,
        MarmotDen,
        GehennaTeleporter,
        ForceCommanderGoraxsCorpse,
        ZethGorTower,
        UnguardedSummoningSite,
        LockedWyvernCage,
        GorgromsCorpse,
        DeathsDoorFelCannon,
        WrithingMoundSummoningCircle,
        AltarOfGocAndThatGocHasNotBeenSummoned,
        TheRavensClaw,
        ArakkoaShrine,
        SoulgrindersAltar,
        ShartuulsTransporterPlatform,
        ShipwreckDebris,
        BlackhoofVillageWindmill,
        GrimtotemTent,
        HyalFamilyMonument,
        BurningTrollHut,
        EntranceToOnyxiasLair,
        SwamplightManorDock,
        TheWyrmcallersPlatform,
        ShatteredStrandCannon,
        CannonOnNorthernAllianceWall,
        TheThanesPyre,
        FrozenWaterfall,
        ProximityToPlaguehoundCagesAtVengeanceLanding,
        StandingAtTheBoothCounter,
        CauldronOfVrykulBlood,
        HarrissPlagueSamples,
        YouToBeCloserToPlaguehoundCages,
        BrokenTablet,
        SunkenBoat,
        CenterOfBaleheim,
        BrewfestMugRequest,
        WaltsTransportRune,
        IronDwarfTransportRune,
        LeyLinesOfQuelDanas,
        RazorthornDirtMound,
        CrystalWard,
        LegionTeleporter,
        HauthaasAnvil,
        VrykulBurialMound,
        WestriftSeismicAnomaly,
        JsbReusePost240,
        NerubArSinkhole,
        SnarlfangsTotem,
        EnKilahCauldron,
        YouToBeAtOrNearTheFrontOfAKvaldirShip,
        YouToBeStandingAtTheEndOfWarsongJetty,
        ImprisonedBerylSorcerer,
        BerylForceShield,
        DenOfDyingPlagueCauldron,
        SouthSinkhole,
        YouToBeAtTheCrossroadsEastOfWarsongHoldWithAnAllianceDeserterInTow,
        YouToBeStandingNextToBloodmageLaurithAtTheBloodsporePlains,
        ShatteredSunPortal,
        ShatteredSunPortal2,
        CrashedFlyingMachine,
        GeyserFieldsSteamVent,
        NexusDimensionalRift,
        FarshireGrain,
        SaragosasLanding,
        ProximityToAScourgeSinkhole,
        NorthwestNexusEntrance,
        DrakurusBrazier,
        EastEndOfThorModanTunnel,
        TuaKeasFishingHook,
        ToaluUsBrazier,
        FizzcrankPracticeParachuteZone,
        FizzcrankParatrooperTeleporter,
        LeyLineFocusOnTheBeach,
        LeyLineFocusInTheLothalorWoodlands,
        LeyLineFocusUnderTheLake,
        DrakilJinGongs,
        MarkedColdwindTree,
        CenterOfThePitUnderTheSurgeNeedle,
        DepthsBelowVordrassilsRemains,
        DepthsBelowVordrassilsLimb,
        DepthsBelowVordrassilsTears,
        HanselBauer,
        GromTharsChallengingArea,
        WintergardeGryphonStation,
        NewHearthglenLumbermill,
        VordrassilsSapling,
        Basecamp,
        ObsidianDragonshrineExitPath,
        YouToBeStandingNextToSiegeEngineerQuarterflash,
        NecromanticRune,
        YouToBeStandingAtOneOfTheEntrancePointsToWintergardeMine,
        SchoolOfNorthernSalmon,
        YouToBeStandingInTheCenterOfTheRuinsAtTheForgottenShore,
        YouToBeAtTheFrontOfTheWintergardeMausoleum,
        RuunasCrystalBall,
        SquirePercy,
        ThatYouBeCloserToAlystrosTheVerdantKeeper,
        FrostmourneAltar,
        ThatYouBeOnTheSandsOfTheBronzeDragonshrine,
        VrykulHawkRoost,
        ScourgedMummyFire,
        DrakkariRitualStatue,
        FinklesteinsCauldron,
        MistwhisperWeatherShrine,
        OfferingBowl,
        DrakkariPedestal,
        FallenLog,
        AncientDirtMound,
        NerubianCrater,
        Runeforge,
        LandingPad,
        Scourgewagon,
        QuetzLunsCorpseAndThatTheProphetOfQuetzLunBePresentAndUnengaged,
        AltarOfKartak,
        GreatLightningStone,
        WarlordZolMazPresentAndUnengagedInCombat,
        TopOfTheSuntouchedPillar,
        ConvocationSummoningCircle,
        SoakedFertileDirt,
        TopOfSholazarPillar,
        TopOfTheGlimmeringPillar,
        ExposedLifebloodPillarCrystal,
        UzoDeathcaller,
        ArchbishopLandgrensCorpseAndLordCommanderAreteNotBePresent,
        SchoolOfTastyReefFish,
        MagmawyrmResurrectionChamber,
        FrostgutsAltar,
        GarmTeleporter,
        ThaneUfrangTheMightyPresentAndSeated,
        NorthernIceSpike,
        IcyCrater,
        VanguardInfirmary,
        Snowdrift,
        TheBroodmothersNest,
        Const350,
        ThaneIllskarBePresentAndThatHeAndHisChampionsNotBeEngagedInBattle,
        PileOfCrusaderSkulls,
        MalykrissFurnace,
        AhnKahetBrazier,
        SanctumOfReanimationSlab,
        DalaranFountain,
        YmirheimPeakSkulls,
        MordRetharPlagueCauldron,
        GrimkorsOrb,
        CultistsCauldron,
        AlumethsSoulstone,
        YouToBeNearALexiconOfPower,
        SmolderingScrap,
        AltarOfTheEbonDepths,
        CorpseOfTheFallenWorg,
        UnlitSignalFire = 1596,
        DrakMarOfferingRing,
        TournamentStables = 1599,
        BlackKnightsGryphon = 1601,
        StoneBlock,
        GhostlyCookingFire = 1613,
        MysteriousSnowMound = 1618,
        MistcallersCave = 1620,
        TualiqMonuments,
        TheDeckOfBorsFury,
        End
    }
}
