using System;

namespace Styx
{
	public enum SkillLine
	{
		Frost = 6,
		Fire = 8,
		Arms = 26,
		Combat = 38,
		Subtlety,
		Swords = 43,
		Axes,
		Bows,
		Guns,
		BeastMastery = 50,
		HunterSurvival,
		Maces = 54,
		TwoHandedSwords,
		Holy,
		ShadowMagic = 78,
		Defense = 95,
		LanguageCommon = 98,
		DwarvenRacial = 101,
		LanguageOrcish = 109,
		LanguageDwarven = 111,
		LanguageDarnassian = 113,
		LanguageTaurahe = 115,
		DualWield = 118,
		TaurenRacial = 124,
		OrcRacial,
		NightElfRacial,
		FirstAid = 129,
		FeralCombat = 134,
		Staves = 136,
		LanguageThalassian,
		LanguageDraconic,
		LanguageDemonTongue,
		LanguageTitan,
		LanguageOldTongue,
		Survival,
		HorseRiding = 148,
		WolfRiding,
		TigerRiding,
		RamRiding = 152,
		Swimming = 155,
		TwoHandedMaces = 160,
		Unarmed = 162,
		Marksmanship,
		Blacksmithing,
		Leatherworking,
		Alchemy = 171,
		TwoHandedAxes,
		Daggers,
		Thrown = 176,
		Herbalism = 182,
		Retribution = 184,
		Cooking,
		Mining,
		PetImp = 188,
		PetFelhunter,
		Tailoring = 197,
		Engineering = 202,
		PetSpider,
		PetVoidwalker,
		PetSuccubus,
		PetInfernal,
		PetDoomguard,
		PetWolf,
		PetCat,
		PetBear,
		PetBoar,
		PetCrocolisk,
		PetCarrionBird,
		PetCrab,
		PetGorilla,
		PetRaptor = 217,
		PetTallstrider,
		RacialUndead = 220,
		Crossbows = 226,
		Wands = 228,
		Polearms,
		PetScorpid = 236,
		Arcane,
		PetTurtle = 251,
		Assassination = 253,
		Fury = 256,
		Protection,
		Protection2 = 267,
		PetGenericHunter = 270,
		PlateMail = 293,
		LanguageGnomish = 313,
		LanguageTroll = 315,
		Enchanting = 333,
		Demonology = 354,
		Affliction,
		Fishing,
		Enhancement = 373,
		ShamanRestoration,
		ElementalCombat,
		Skinning = 393,
		Mail = 413,
		Leather,
		Cloth,
		Shield = 433,
		FistWeapons = 473,
		RaptorRiding = 533,
		MechanostriderPiloting = 553,
		UndeadHorsemanship,
		Restoration = 573,
		Balance,
		Destruction = 593,
		DruidHoly,
		Discipline = 613,
		Lockpicking = 633,
		PetBat = 653,
		PetHyena,
		PetBirdofPrey,
		PetWindSerpent,
		LanguageGutterspeak = 673,
		KodoRiding = 713,
		RacialTroll = 733,
		RacialGnome = 753,
		RacialHuman,
		Jewelcrafting,
		BloodElfRacial,
		PetEventRemoteControl = 758,
		LanguageDraenei,
		DraeneiRacial,
		PetFelguard,
		Riding,
		PetDragonhawk,
		PetNetherRay,
		PetSporebat,
		PetWarpStalker,
		PetRavager,
		PetSerpent,
		Internal,
		DkBlood,
		DkFrost,
		DkUnholy,
		Inscription,
		PetMoth = 775,
		Runeforging,
		Mounts,
		Companions,
		PetExoticChimaera = 780,
		PetExoticDevlisaur,
		PetGhoul,
		PetExoticSilithid,
		PetExoticWorm,
		PetWasp,
		PetExoticRhino,
		PetExoticCoreHound
	}
}
