using System;

namespace Styx
{
	public enum StatTypes
	{
		Armor,
		HolyResistance,
		FireResistance,
		NatureResistance,
		FrostResistance,
		ShadowResistance,
		ArcaneResistance,
		AttackPower2,
		MeleeAttackPower,
		RangedAttackPower2,
		AttackPowerInForms,
		Mana,
		Health,
		Agility = 14,
		Strength,
		Intellect,
		Spirit,
		Stamina,
		DefenseRating = 23,
		DodgeRating,
		ParryRating,
		BlockRating,
		HitRatingMelee,
		HitRatingRanged,
		HitRatingSpell,
		CriticalStrikeRatingMelee,
		CriticalStrikeRatingRanged,
		CriticalStrikeRatingSpell,
		HitAvoidanceRatingMelee,
		HitAvoidanceRatingRanged,
		HitAvoidanceRatingSpell,
		CriticalStrikeAvoidanceRatingMelee,
		CriticalStrikeAvoidanceRatingRanged,
		CriticalStrikeAvoidanceRatingSpell,
		HasteRatingMelee,
		HasteRatingRanged,
		HasteRatingSpell,
		HitRating,
		CriticalStrikeRating,
		HitAvoidanceRating,
		CriticalStrikeAvoidanceRating,
		ResilienceRating,
		HasteRating,
		ExpertiseRating,
		AttackPower,
		RangedAttackPower,
		BonusHealing = 52,
		BonusDamage,
		ManaRegeneration,
		ArmorPenetrationRating,
		SpellPower,
		HealthPer5Sec,
		SpellPenetration,
		BlockValue,
		BlockValue2,
		ManaPer5Sec,
		RagePer5Sec,
		FocusPer5Sec,
		EnergyPer5Sec,
		HappinessPer5Sec,
		RunesPer5Sec,
		RunicPowerPer5Sec,
		HealthPer5Sec2,
		MetaSocket,
		RedSocket,
		YellowSocket,
		BlueSocket
	}
}
