using System;

namespace Styx
{
	public enum WoWItemStatType
	{
		None = -1,
		Health = 1,
		Mana,
		Agility,
		Strength,
		Intellect,
		Spirit,
		Stamina,
		DefenseRating = 12,
		DodgeRating,
		ParryRating,
		ShieldBlockRating,
		MeleeHitRating,
		RangedHitRating,
		SpellHitRating,
		MeleeCriticalStrikeRating,
		RangedCriticalStrikeRating,
		SpellCriticalStrikeRating,
		MeleeHitAvoidanceRating,
		RangedHitAvoidanceRating,
		SpellHitAvoidanceRating,
		MeleeCriticalAvoidanceRating,
		RangedCriticalAvoidanceRating,
		SpellCriticalAvoidanceRating,
		MeleeHasteRating,
		RangedHasteRating,
		SpellHasteRating,
		HitRating,
		CriticalStrikeRating,
		HitAvoidanceRating,
		CriticalAvoidanceRating,
		ResilienceRating,
		HasteRating,
		ExpertiseRating,
		AttackPower,
		RangedPower,
		FeralAttackPower,
		DamageDone,
		HealingDone,
		ManaEvery5Seconds,
		ArmorPenetration,
		SpellPower,
		HealthEvery5Seconds,
		SpellPenetration,
		BlockValue
	}
}
